[package]
name = "ak_os-kernel"
version = "0.1.0"
edition = "2021"

[features]
default = ["uefi_boot"]

uefi_boot = ["uefi"]

[dependencies]
uefi = { version = "0.16", default-features = false, features= ["alloc"], optional = true }
log = "0.4"
x86_64 = "0.14"
bootloader_api = { git = "https://github.com/rust-osdev/bootloader", branch = "next" }
linked_list_allocator = "0.10"
noto-sans-mono-bitmap = "0.1"
spinning_top = "0.2"
conquer-once = { version = "0.3", default-features = false }
